### ISSUE TITLE
Installer does not boot on MacPro3,1

### ISSUE THREAD

**Issue by schreiberstein** [speediegamer/the81project#1] opened 2021-03-14 20:43 UTC
Hello!

Thank you for putting together this interesting project / tool!
I truly appreciate these niche efforts.

I found out about it today and tested the DMG image you created on my MacPro3,1 via a USB stick.
When I first got it two years ago, I tried my best to install Tiger on it but I could not get it to work at all.
(I am a fairly competent "hackintosher" and UNIX user so I tried many different things such as replacing Kexts, etc.)
I thought your tool / distribution might be the solution to my quest, but I was unable to boot the installer.

It panics almost immediately:
panic(cpu 0 caller 0x003AB7C3): Unable to find driver for this platform: "ACPI".
[backtrace...]

I can boot into single user mode by holding the "s" key. The shell works fine. But when I exit the shell and expect launchd to load the actual system components, the system just freezes after reporting something about AirPort. (Looks highly unrelated to me.) I do not get a panic message there or in verbose mode.
The panic occurs when I start in the normal mode (no keys pressed) or in safe mode (holding shift). The latter mode allowed me to read the backtrace.

Do you have any idea what the problem could be?

System:
MacPro3,1 from 2008
4GB RAM
Nvidia GeForce 8800 GT

If I could get Tiger to run, I could run every single Mac OS X Intel release on this machine. (Tiger -> Big Sur)

Have a great day!
Cheers,
schreiberstein

**Comment by speediegamer** [comment] 2021-03-15 21:12
This is an issue I knew potentially existed. In order to fix this, you'd need a bootloader like Clover or OpenCore in the ESP. This is an easy fix and older versions of The81Project even had it. I have only tested this on my Early 2008 iMac and it booted just fine.
I'll make a new image which has a bootloader in the ESP. I thought I fixed this by using a different Tiger image as base but I guess I didn't. I had this issue before on my 8,1 but I fixed it by using a different image so I thought that would apply to more Macs.

Regardless, will be fixed in an alternate version.

**Comment by schreiberstein** [comment] 2021-03-15 21:45
Thanks for your reply!
Sadly, this version did not work for me either.
I was able to boot into Clover and start OS X, but it crashed in the same way as before.
It seems like this Clover setup lacks a theme so mostly all menus are broken (like ticking checkboxes, etc.)
I sincerely hoped there would be a semi-vanilla way of getting Tiger to run on this machine, without using an external bootloader.
If I had more time, I would experiment with OpenCore, but there are many other projects on my plate.
In case you cook up something new, as you described, I will be glad to test it.

Have a great evening!
Alex

**Comment by schreiberstein** [comment] 2021-03-15 22:12
Also, your approach of including VirtualSMC.kext to fake the SMBIOS won't work since Lilu is not included and I am sure it won't work on Tiger. Was unable to find a copy of FakeSMC for Tiger right now. Otherwise, it would be possible to perhaps fake the SMBIOS to MacPro2,1 and boot.

**Comment by speediegamer** [comment] 2021-03-16 23:00
Thank you very much for your interest. VirtualSMC was not even intended to be on, it was just an oversight on my part although it doesn't do any harm, at least not in my testing. However, the install DVD used as base is intended for an iMac7,1 aka the Mid 2007 iMac. Clover was used to fake the SMBIOS for a Mid 2007 iMac.  So it wouldn't matter what system it was running on as long as it's a machine with specs that could theoretically boot Tiger because the SMBIOS is faked anyway. It is possible that the issue is just that the SMBIOS for the 7,1 won't boot on Mac Pro computers because of the processors in those machines. ACPI also seems to be a CPU error but I could be wrong there. I'll do some more testing and I might add multiple configs in the next update if this seems to be the problem.

**Comment by speediegamer** [comment] 2021-04-08 13:08
May have been fixed with version 5.0 which is a complete rebuild. Closing this for now, I'll hopefully get some testing done to determine if it actually works. If it still doesn't work, please open another issue.

https://github.com/speediegamer/the81project/releases/tag/5.0.0

**Closed by speediegamer** 2021-04-08 13:08 UTC
